config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  unauthenticated do
    root :to => 'pages#home'
  end

  authenticated do
    root to: "pages#dashboard", as: "dashboard"
  end

  resources :users, only: [:show, :edit, :update] do
    resources :footprint, only: [:new, :create, :update]
  end

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  resources :challenges, only: [:index, :show] do
    resources :user_challenges, only: [:create, :update]
    resources :invites, only: [:new, :create, :update, :destroy]
  end
  resources :user_challenge_steps, only: [:update]

  resources :categories
  resources :tips, only: [:index, :show]
  resources :friendships, only: [:index, :new, :create, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :challenges, through: :user_challenges
  has_many :user_challenges
  has_one :footprint
  has_many :invitations, class_name: self.to_s, as: :invited_by
  has_many :invites, class_name: 'Invite', foreign_key: 'invitee_id'
  has_many :invites, class_name: 'Invite', foreign_key: 'inviter_id'

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Friendship'
  has_many :followeds, through: :followed_users #followeds are people I follow
  has_many :following_users, foreign_key: :followed_id, class_name: 'Friendship'
  has_many :followers, through: :following_users #followers are people that follow me

  has_one_attached :photo

  after_create :create_footprint
  after_commit :add_default_avatar, on: [:create, :update]

  validates :email, :encrypted_password, presence: true
  validates :email, format: { with: Devise.email_regexp }

private

  def create_footprint
      Footprint.create(user_id: self.id, score: rand(4000..5000))
  end

  def add_default_avatar
    unless photo.attached?
      self.photo.attach(io: File.open(Rails.root.join("app", "assets", "images", "avatar_default.svg")), filename: 'avatar_default.svg' , content_type: "image/svg")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @show_page = true
    @user = User.find(params[:id])
    @user_challenges = UserChallenge.where(user_id: @user.id)
    @done_challenges = @user_challenges.where(status: "completed")

    @total = 0
    @done_challenges.each do |user_chall|
      @total = @total + user_chall.challenge.points
    end

    @ongoing_challenges = @user_challenges.where(status: "in_progress")
    @user_footprint = Footprint.find_by(user_id: current_user.id)
    @score = @user_footprint&.score
    @friendships = Friendship.where(accepted: true)
    @followers_count = @user.followers.length
    @following_count = @user.followeds.length

    @current_follower = @friendships.where(follower_id: current_user.id)
    @followed_user = @current_follower.find_by(followed_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user)
  end

  def follow
    @user = User.find(params[:id])
    current_user.followeds << @user
    redirect_back(fallback_location: user_path(@user))
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.find_by(followed_id: @user.id).destroy
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :photo)
  end

end

app/views/users/show.html.erb
<div class="container container-profile min-height d-flex">
  <!-- Left side -->
  <div class="col-4">
    <!-- User card -->
    <div class="user-card background-blue position-relative">
      <span class="avatar-profile position-absolute">
        <%= cl_image_tag @user.photo.key, crop: :scale %>
      </span>
      <h3><%= @user.username %></h3>
      <div class="d-flex">
        <div class="col text-center vertical-separator">
          <p> Followers</p>
          <% if current_user == @user %>
            <p class="secular-one numbers-big"><%= link_to @followers_count, friendships_path %></p>
          <% else %>
            <p class="secular-one numbers-big"><%= @followers_count %></p>
          <% end %>
        </div>
        <div class="col text-center">
          <p>Following</p>
          <% if current_user == @user %>
            <p class="secular-one numbers-big"><%= link_to @following_count, friendships_path %></p>
          <% else %>
            <p class="secular-one numbers-big"><%= @following_count %></p>
          <% end %>
        </div>
      </div>
      <% if @done_challenges.empty? %>
        <p class="text-small">
          No challenge completed yet.
        <br>Joined on <%= @user.created_at.strftime("%b %d, %Y") %>
        </p>
      <% else %>
        <p class="text-small">Last challenge completed on
        <%= @done_challenges.last.updated_at.strftime("%b %d, %Y") %> <br>Joined on <%= @user.created_at.strftime("%b %d, %Y") %></p>
      <% end %>
      <!-- Edit/FOLLOW UNFOLOW link -->
      <% if current_user == @user %>
        <%= link_to user_path(@user), "data-toggle" => "modal", 'data-target' => '#editModal' do %>
          <div class="button-outline-blue margin-bottom-none">
            <p>Edit</p>
          </div>
        <% end %>
        <!-- Edit modal -->
        <div class="modal fade" id="editModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">My profile information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= simple_form_for(@user) do |f| %>
                <div class="modal-body">
                  <%= f.input :username %>
                  <%= f.input :email %>
                  <%= f.input :photo, as: :file %>
                </div>
                <div class="modal-footer">
                  <%= link_to 'Back', user_path(@user), class: "button-outline" %>
                  <%= f.button :submit, 'Save changes', class: "button" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <!--  end of modal -->
      <% elsif current_user.followeds.include?(@user) %>
        <%= link_to unfollow_user_path, method: :post do %>
          <div class="button-outline-blue margin-bottom-none">
            <p>Unfollow</p>
          </div>
        <% end %>
      <% else %>
        <%= link_to follow_user_path, method: :post do %>
          <div class="button-outline-blue margin-bottom-none">
            <p>Follow</p>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- Achievements section -->
    <div>
      <div class="mt-5">
        <h2>Achievements</h2>
        <hr class="profile">
        <div class="badges d-flex align-items-center p-2">
          <h5 class="mr-5">Badges</h3>
          <div class="points">
            <% @done_challenges.each do |count| %>
              <i class="fas fa-leaf"></i>
            <% end %>
          </div>
        </div>
        <div class="badges d-flex align-items-center p-2">
          <h5 class="mr-5">Points</h3>
          <div class="points"><%= @total %></div>
        </div>
      </div>
    </div>
  </div>

  <!-- Right side -->
  <div class="grid">
    <div class="row">
      <div class="col">
        <!-- Carbon footprint -->
          <div>
            <h2>Completed challenges</h2>
            <hr class="profile">
              <% @done_challenges.each do |user_challenge| %>
                <div class="d-flex justify-content-between align-items-center px-2 my-3 border border-primary">
                  <div class="mx-2">
                    <%= link_to user_challenge.challenge.name, challenge_path(user_challenge.challenge) %>
                  </div>
                  <div class="align-middle">
                    <div class="align-middle text-center"><%= user_challenge.challenge.points%></div>
                    <div class="align-middle text-center"> points</div>
                  </div>
                </div>
              <% end %>
          </div>
      </div>
    </div>
        <!-- Ongoing challenges -->
    <div class="row">
      <div class="col">
          <div>
            <h2>Ongoing challenges</h2>
            <hr class="profile">
              <% @ongoing_challenges.each do |user_challenge| %>
                <div class="d-flex justify-content-between align-items-center px-2 my-3 border border-primary">
                  <div class="mx-2">
                    <%= link_to user_challenge.challenge.name, challenge_path(user_challenge.challenge) %>
                  </div>
                  <div class="align-middle">
                    <div class="align-middle text-center"><%= user_challenge.challenge.points%></div>
                    <div class="align-middle text-center"> points</div>
                  </div>
                </div>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</div>



<!-- <div>
            <% if @score %>
              <p><%= @score %></p>
              <div class="progress" style="height: 20px;">
              <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="<%= (5000 - @score)/50 %>" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            <% end %>
          </div>
-->