config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  unauthenticated do
    root :to => 'pages#home'
  end

  authenticated do
    root to: "pages#dashboard", as: "dashboard"
  end

  resources :users, only: [:show, :edit, :update] do
    resources :footprint, only: [:new, :create, :update]
  end

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  resources :challenges, only: [:index, :show] do
    resources :user_challenges, only: [:create, :update]
    resources :invites, only: [:new, :create, :update, :destroy]
  end
  resources :user_challenge_steps, only: [:update]

  resources :categories
  resources :tips, only: [:index, :show]
  resources :friendships, only: [:index, :new, :create, :update, :destroy]
end

app/views/pages/dashboard.html.erb
<!-- User signed in view: start -->
<div class="container container-margin">
  <!-- Welcome line -->
  <h1 class="welcome-line">Welcome <span class="username-green"><%= current_user.username %> <i class="fas fa-seedling"></i></span></h1>
  <!-- Carbon footprint -->
  <div class="secondary-container">
    <h2 class="dashboard">Carbon footprint</h2>
    <div class="footprint-container">
      <div class="score-card">
        <p>Your score</p>
        <% if @score %>
          <p class="score"><%= @score %></p>
        <% end %>
      </div>
      <div class="results">
        <p>Your lifestyle emits 531kg of CO2 per year.</p>
        <div class="percentages">
          <div class="percentage">
            <div class="percentage-details">
              <p>bathroom</p>
              <p class="level-percent">3%</p>
            </div>
            <div class="result-bar">
              <div class="gauge category-bathroom"></div>
            </div>
          </div>
          <div class="percentage">
            <div class="percentage-details">
              <p>daily</p>
              <p class="level-percent">11%</p>
            </div>
            <div class="result-bar">
              <div class="gauge category-daily"></div>
            </div>
          </div>
          <div class="percentage">
            <div class="percentage-details">
              <p>energy</p>
              <p class="level-percent">15%</p>
            </div>
            <div class="result-bar">
              <div class="gauge category-energy"></div>
            </div>
          </div>
          <div class="percentage">
            <div class="percentage-details">
              <p>food</p>
              <p class="level-percent">22%</p>
            </div>
            <div class="result-bar">
              <div class="gauge category-food"></div>
            </div>
          </div>
          <div class="percentage">
            <div class="percentage-details">
              <p>shopping</p>
              <p class="level-percent">18%</p>
            </div>
            <div class="result-bar">
              <div class="gauge category-shopping"></div>
            </div>
          </div>
          <div class="percentage">
            <div class="percentage-details">
              <p>transports</p>
              <p class="level-percent">31%</p>
            </div>
            <div class="result-bar">
              <div class="gauge category-transports"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Challenges -->
  <div class="secondary-container">
    <h2 class="dashboard">Challenges</h2>
    <div class="dashboard-challenge-cards">
      <% @user_challenges.each do |user_challenge| %>
        <% if user_challenge.status == "in_progress" %>
          <%= link_to challenge_path(user_challenge.challenge) do %>
            <div class="dashboard-challenge-card-progress">
              <div>
                <h4><%= user_challenge.challenge.name %></h4>
                <p class="challenge-card-category"><%= user_challenge.challenge.category.name.downcase %></p>
              </div>
              <div class="status">
                <p class="in-progress">In progress</p>
                <p>Nail it now!</p>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= link_to challenge_path(user_challenge.challenge) do %>
            <div class="dashboard-challenge-card-completed">
              <div>
                <h4><%= user_challenge.challenge.name %></h4>
                <p class="challenge-card-category background-green"><%= user_challenge.challenge.category.name.downcase %></p>
              </div>
              <div class="status">
                <p class="completed">Completed</p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <%= link_to challenges_path do %>
        <div class="dashboard-challenge-button">
          <p class="plus">+</p>
          <p>Start a new challenge</p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="secondary-container tips-friends">
    <!-- Tips -->
    <div>
      <h2 class="dashboard">We've got some tips for you</h2>
      <div class="tip-suggestions">
        <% @random_tips.each do |tip| %>
          <div class="tip-card-dashboard" data-category="<%= tip.category.name.downcase %>">
            <%= image_tag("tip-#{tip.image}.jpg") %>
            <div class="tip-card-dashboard-infos">
              <h6><%= link_to tip.title, tip_path(tip) %></h6>
              <h5 class="tip-card-category-dashboard d-inline-flex"><%= tip.category.name.downcase %></h5>
              <p><%= tip.description.to_s.truncate(150) %></p>
              <p class="read-more"> <%= link_to "Read more", tip_path(tip) %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <!-- Friends zone: start -->
    <div class="friends-container">
      <!-- Invitations to challenges -->
      <div>
        <h2 class="dashboard">You've been challenged!</h2>
        <div class="invitation-cards">
          <% if @open_invites != [] %>
            <% @open_invites.each do |invite| %>
              <div class="invitation-card">
                <div class="avatar-friend">
                  <%= cl_image_tag invite.inviter.photo.key, crop: :scale %>
                </div>
                <div class="invitation-card-info">
                  <p><%= link_to "#{invite.inviter.username}", user_path(invite.inviter.id) %> invited you to participate to <span class="secular-one"><%= link_to invite.challenge.name, challenge_path(invite.challenge.id) %></span>.</p>
                  <div class="">
                    <%= link_to "Accept", challenge_invite_path(invite.challenge, invite),
                                              method: :patch,
                                              class: "button-invitation accept" %>
                    <%= link_to "Decline", challenge_invite_path(invite.challenge, invite),
                                              class: "button-invitation decline",
                                              method: :delete %>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <div class="no-invitation">
              <p class="hand"><i class="far fa-hand-peace"></i></p>
              <p class="secular-one chill">Chill!</p>
              <p>Enjoy the empty inbox.</p>
            </div>
          <% end %>
        </div>
      </div>
      <!-- Followers invitations -->
      <div>
        <h2 class="dashboard margin-top">They want to stalk you</h2>
        <div class="invitation-cards">
          <% if @open_friendships != [] %>
            <% @open_friendships.each do |friendship| %>
              <div class="invitation-card">
                <div class="avatar-friend">
                  <%= cl_image_tag friendship.follower.photo.key, crop: :scale %>
                </div>
                <div class="invitation-card-info">
                  <p><span class="secular-one"><%= link_to "#{friendship.follower.username}", user_path(friendship.follower.id) %></span> wants to follow you.</p>
                  <div class="">
                    <%= link_to "Accept", friendship_path(friendship),
                                          method: :patch,
                                          class: "button-invitation accept" %>
                    <%= link_to "Decline", friendship_path(friendship),
                                          method: :delete,
                                          class: "button-invitation decline" %>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <div class="no-invitation">
              <p class="hand"><i class="far fa-hand-peace"></i></p>
              <p class="secular-one chill">Chill!</p>
              <p>Enjoy the empty inbox.</p>
            </div>
          <% end %>
        </div>
      </div>
      <!-- Add a friend -->
      <!-- Button trigger modal -->
      <button type="button" class="button-outline-blue padding" data-toggle="modal" data-target="#exampleModal">
        Find a friend to stalk
      </button>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Follow your friends!</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= simple_form_for [@friendship] do |f| %>
                <%= f.association :followed, label: 'Find your friend', label_method: :username, input_html: { class: 'select2' } %>
                <%= f.button :submit, 'Send invitation', class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Friends zone: end -->
  </div>
</div>
<!-- User signed in view: end -->

app/views/pages/home.html.erb
<!-- User signed out view -->
<div class="homepage2 margin-top">
  <div class="container min-height">
    <br>
    <br>
    <h1 class="landing-page baseline">Change is now</h1>
    <p class="landing-page">Get a clear idea of your lifestyle footprint, improve it and challenge yourself and your friends!</p>
    <p class="landing-page">Change is now, and it is fun. Sign up now!</p>
    <br>
    <%= link_to "Sign up", new_user_registration_path, class: "button" %>
  </div>
</div>