config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  unauthenticated do
    root :to => 'pages#home'
  end

  authenticated do
    root to: "pages#dashboard", as: "dashboard"
  end

  resources :users, only: [:show, :edit, :update] do
    resources :footprint, only: [:new, :create, :update]
  end

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  resources :challenges, only: [:index, :show] do
    resources :user_challenges, only: [:create, :update]
    resources :invites, only: [:new, :create, :update, :destroy]
  end
  resources :user_challenge_steps, only: [:update]

  resources :categories
  resources :tips, only: [:index, :show]
  resources :friendships, only: [:index, :new, :create, :update, :destroy]
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :category
  has_many :users, through: :user_challenges
  has_many :challenge_steps, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :pg_search,
    against: [:name, :description],
    associated_against: {
        category: [ :name ]
    },
    using: {
      tsearch: {prefix: true}
  }
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @challenges = Challenge.includes(:category).all
    @categories = Category.all
    if params[:query].present?
      @challenges = Challenge.pg_search(params[:query])
      @placeholder = params[:query]
    else
      @challenges = Challenge.all
      @placeholder = "Search for a challenge"
    end
  end

  def show
    @challenge = Challenge.find(params[:id])
    @show_page = true
    @challenge_started = challenge_started?
    if @challenge_started
      user_challenges = UserChallenge.where(user_id: current_user.id)
      @user_challenge = user_challenges.find_by(challenge_id: params[:id])
      @challenge_steps = @challenge.challenge_steps
      @value = @user_challenge.user_challenge_steps.where(status:"completed").count.to_f / @challenge_steps.count.to_f * 100
      @value = @value.floor
    end

    @challenge_steps = ChallengeStep.where(challenge_id: params[:id])
    @challenge_completed = challenge_completed?

    @users = Friendship.where(followed: current_user.id)
    @invite = Invite.new

    @participants_count = participants_count + @challenge.participant_base

    @invites_count = Invite.where(inviter_id: current_user.id)
    @invites_challenge = @invites_count.where(challenge_id: params[:id])
    @friends = @invites_challenge.where(accepted: true).length
  end

  private

  def challenge_started?
    user_challenges = UserChallenge.where(user_id: current_user.id)
    user_challenge = user_challenges.find_by(challenge_id: params[:id])
    user_challenge&.status == "in_progress"
  end

  def challenge_completed?
    user_challenges = UserChallenge.where(user_id: current_user.id)
    user_challenge = user_challenges.find_by(challenge_id: params[:id])
    user_challenge&.status == "completed"
  end

  def participants_count
    user_challenges = UserChallenge.where(challenge_id: params[:id])
    open_user_challenges_count = user_challenges.where(status: "in_progress").length
    return open_user_challenges_count
  end
end

app/views/challenges/index.html.erb
<div class="category-cards">
  <% @categories.each do |category| %>
    <div class="category-card <%=category.name.downcase%>" data-category="<%=category.name.downcase%>">
      <h2 data-category="<%=category.name.downcase%>"><%= category.name %></h2>
    </div>
  <% end %>
</div>
<!-- Search bar -->
<div class="search-bar">
  <%= simple_form_for :search, url: challenges_path, method: :get do |f| %>
    <div class="search-form-control input-group form-group mb-4">
      <input class="form-control string required blue-border rounded-0" type="text" placeholder="<%= @placeholder %>" name="[query]" id="pg_search" />
      <button class="btn bg-transparent" type="submit">
        <i class="fas fa-times-circle"></i>
      </button>
      <div class="input-group-append">
        <button name="button" type="submit" class="input-group-text green lighten-3 rounded-0" id="basic-text1">
          <span ><i class="fas fa-search text-white"
            aria-hidden="true"></i></span>
        </button>
      </div>
    </div>
  <% end %>
</div>

<div class="challenge-cards">
  <% @challenges.each do |challenge| %>
  <div class="challenge-card" data-category="<%=challenge.category.name.downcase%>">
    <%= image_tag("#{challenge.image}") %>
    <div class="challenge-card-infos">
      <h2><%= link_to challenge.name, challenge_path(challenge) %></h2>
      <h3 class="category-tip-dashboard"><%= challenge.category.name.downcase %></h3>
      <p><%= challenge.description.to_s.truncate(80) %><%= link_to "     Read more", challenge_path(challenge) %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/challenges/show.html.erb
<div class="banner">
  <%= image_tag("#{@challenge.image}") %>
  <div class="banner-infos">
    <h1><%= @challenge.name %></h1>
    <p class="d-inline-flex category"><%= @challenge.category.name.downcase %></p>
  </div>
</div>

<div class="container container-challenge">

  <div class="d-flex">
    <!-- Left side -->
    <div class="col-7">
      <h3>Overview</h3>
      <p class="challenge-description"><%= @challenge.description %></p>
      <div class="challenge-highlights">
        <div class="d-flex highlight">
          <i class="fas fa-calendar-check"></i>
          <p>You will need <%= @challenge.duration %> weeks to complete this challenge.</p>
        </div>
        <div class="d-flex highlight">
          <i class="fas fa-medal"></i>
          <p><%= @challenge.benefit %></p>
        </div>
        <div class="d-flex highlight">
          <i class="fas fa-seedling"></i>
          <p>Offset your carbon footprint by <%= @challenge.points %> points.</p>
        </div>
      </div>
      <div class="d-flex my-4">
        <div class="participants">
          <p>Participants</p>
          <p class="number-participants"><%= @participants_count %></p>
        </div>
        <div class="d-flex flex-column justify-content-end px-4">
          <div class="d-flex align-items-center">
            <span class="avatar-friends"><%= image_tag("avatar_default.svg") %></span>
            <% if @friends > 1 %>
            <p class="friends"><%= @friends %> friends are completing this challenge</p>
            <% elsif @friends == 0 %>
            <p class="friends"> You have no friend completing this challenge</p>
            <% else %>
            <p class="friends"> <%= @friends %> friend is completing this challenge</p>
            <% end %>
          </div>

          <!-- Button trigger modal -->
          <button type="button" class="button-outline-blue padding" data-toggle="modal" data-target="#exampleModal">
            Invite friends
          </button>

          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Take on this challenge together!</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= simple_form_for [@challenge, @invite] do |f| %>
                    <%= f.association :invitee, label: 'Find your friend', label_method: :username, input_html: { class: 'select2 select2-cleo' } %>
                    <%= f.button :submit, 'Send invitation', class: " btn btn-success" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Right side -->
    <div>
      <!-- Progression through challenge: start -->
      <% if @challenge_started %>
        <div class="challenge-progression d-flex flex-column">
          <h3 id="nail-it">Let's nail it!</h3>
          <p class="challenge-description">Here are the different steps you will have to take to complete this challenge:</p>
          <div class="steps background-blue" >
            <% @challenge_steps.each do |step| %>
              <% user_step = @user_challenge.user_challenge_steps.find_by(challenge_step_id: step.id) %>
              <div class="secular-one d-flex flex-column justify-content-between">
                <% if user_step.status == "completed" %>
                  <div class="d-flex justify-content-between">
                    <div class="step-description mb-1">
                      <p><%= step.description  %></p>
                    </div>
                    <div id="good-job" class="align-self-start">
                      <i class="far fa-check-circle"></i>
                    </div>
                  </div>
                <% else %>
                  <div class="d-flex justify-content-between">
                    <p> <%= step.description  %></p>
                    <%= link_to user_challenge_step_path(user_step), method: :patch do %>
                      <button id="btn-step" class="align-self-start" style="outline: none;"><i class="far fa-circle"></i></button>
                    <% end %>
                  </div>
                <% end %>
              </div>
            <% end %>
            <div>
              <progress id="progressbar" max="100" value="<%= @value %>"></progress>
              <p class="progressbar">Your progression: <span class="secular-one"><%= @value %>%</span></p>
            </div>
          </div>
          <%= link_to "Mark challenge as completed", challenge_user_challenge_path(@challenge),
                                          method: :patch,
                                          class: "button-blue padding" %>
        </div>
      <% elsif @challenge_completed %>
        <div class="challenge-progression d-flex flex-column">
          <h3>High five!</h3>
          <div class="outline-grey">
            <p>Challenge completed!</p>
          </div>
          <div class="background-blue">
            <p class="secular-one">You reduced your footprint by <%= @challenge.points %> points by completing this challenge.</p>
            <p>Well done on completing the challenge "<%= @challenge.name %>".</p>
            <p>Thank you for contributing to a greener world.</p>
            <p>Keep up the good work!</p>
            <div class="d-flex justify-content-center">
              <%= link_to "See footprint", root_path, class: "button-footprint" %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="challenge-progression d-flex">
          <%= link_to "Start challenge", challenge_user_challenges_path(@challenge),
                                          method: :post,
                                          id: "start-challenge",
                                          class: "button-primary margin-button" %>
        </div>
      <% end %>
      <!-- Progression through challenge: end -->
    </div>
  </div>
  <hr>
  <div class="link-show">
    <i class="fas fa-hand-point-left"></i><%= link_to "Go back to all challenges", challenges_path  %>
  </div>
</div>