config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  unauthenticated do
    root :to => 'pages#home'
  end

  authenticated do
    root to: "pages#dashboard", as: "dashboard"
  end

  resources :users, only: [:show, :edit, :update] do
    resources :footprint, only: [:new, :create, :update]
  end

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  resources :challenges, only: [:index, :show] do
    resources :user_challenges, only: [:create, :update]
    resources :invites, only: [:new, :create, :update, :destroy]
  end
  resources :user_challenge_steps, only: [:update]

  resources :categories
  resources :tips, only: [:index, :show]
  resources :friendships, only: [:index, :new, :create, :update, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CLEO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <!-- Body -->
  <body class="<%= @home_page ? 'homepage' : ''%>">
    <!-- Header / Navbar -->
    <header>
      <div class="d-flex navbar">
        <div class="container">
          <!-- Logo -->
          <div class="mr-auto logo-navbar">
            <%= link_to root_path do %>
              <%= image_tag("Logo_Cleo_navbar.svg") %>
            <% end %>
          </div>
          <!-- Menu -->
          <% if user_signed_in? %>
          <div class="px-3 title-navbar active" id="dashboard">
           <%= link_to "Dashboard", root_path %>
          </div>
          <div class="px-3 title-navbar" id="challenges">
            <%= link_to " Challenges", challenges_path %>
          </div>
          <div class="px-3 title-navbar" id="tips">
            <%= link_to " Tips", tips_path(:category_id) %>
          </div>
            <!-- Dropdown avatar -->
            <div class="dropdown mr-1">
              <div class="avatar" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= cl_image_tag current_user.photo.key, crop: :scale %>
              </div>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuOffset">
                <%= link_to "Profile", user_path(current_user.id), class: "dropdown-item" %>
                <%= link_to "Settings", root_path, class: "dropdown-item" %>
                <%= link_to "Help", root_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
              </div>
            </div>
          <% else %>
            <%= link_to "Log in", user_session_path, class: "button" %>
          <% end %>
        </div>
      </div>
    </header>

    <%= render 'shared/flashes' %>

    <div class="<%= @show_page ? 'min-height' : 'container container-margin'%>">
      <%= yield %>
    </div>
    <!-- Footer -->

    <footer class="d-flex align-items-center">
      <div class="container d-flex justify-content-end">
        <p>Made with <i class="fas fa-heart"></i> in Brussels © 2020 Cleo</p>
      </div>
    </footer>

  </body>

</html>